#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

# if [ "$current_branch" = "main" ]; then
#   echo "주의! main 브랜치에서 작업 중입니다. feature 브랜치를 잊지 않으셨나요?"
#   exit 1
# fi

yarn lint-staged
